

IF NOT EXISTS (SELECT * FROM dbo.sysusers WHERE [name] = 'EUROPE\CORP-PHXDEVSupport-FIL-LON')
BEGIN
	CREATE USER [EUROPE\CORP-PHXDEVSupport-FIL-LON]
	PRINT 'EUROPE\CORP-PHXDEVSupport-FIL-LON'
END
GO

IF NOT EXISTS (SELECT * FROM dbo.sysusers WHERE [name] = 'EUROPE\CORP-PHXDEVDevs-FIL-LON')
BEGIN
	CREATE USER [EUROPE\CORP-PHXDEVDevs-FIL-LON]
	PRINT 'Created: EUROPE\CORP-PHXDEVDevs-FIL-LON'
END
GO

IF NOT EXISTS (SELECT * FROM dbo.sysusers WHERE [name] = 'EUROPE\CORP-PHXDEVServices-FIL-LON')
BEGIN
	CREATE USER [EUROPE\CORP-PHXDEVServices-FIL-LON]
	PRINT 'Created: EUROPE\CORP-PHXDEVServices-FIL-LON'
END
GO

IF NOT EXISTS (SELECT * FROM sys.database_principals WHERE [name] = 'EUROPE\CORP-PHXDEVSupport-FIL-LON')
BEGIN
	EXEC sp_addrolemember db_datareader, [EUROPE\CORP-PHXDEVSupport-FIL-LON]
	PRINT 'Added: EUROPE\CORP-PHXDEVSupport-FIL-LON'
END
GO

IF NOT EXISTS (SELECT * FROM sys.database_principals WHERE [name] = 'EUROPE\CORP-PHXDEVDevs-FIL-LON')
BEGIN
	EXEC sp_addrolemember db_datareader, [EUROPE\CORP-PHXDEVDevs-FIL-LON]
	PRINT 'Added: EUROPE\CORP-PHXDEVDevs-FIL-LON'
END
GO

IF NOT EXISTS (SELECT * FROM sys.database_principals WHERE [name] = 'EUROPE\CORP-PHXDEVServices-FIL-LON')
BEGIN
	EXEC sp_addrolemember db_datareader, [EUROPE\CORP-PHXDEVServices-FIL-LON]
	PRINT 'Added: EUROPE\CORP-PHXDEVServices-FIL-LON'
END
GO

SELECT * FROM dbo.sysusers WHERE [name] IN 
(
'EUROPE\CORP-PHXDEVDevs-FIL-LON',
'EUROPE\CORP-PHXDEVServices-FIL-LON',
'EUROPE\CORP-PHXDEVSupport-FIL-LON'
)

SELECT * FROM sys.database_principals WHERE [name] IN 
(
'EUROPE\CORP-PHXDEVDevs-FIL-LON',
'EUROPE\CORP-PHXDEVServices-FIL-LON',
'EUROPE\CORP-PHXDEVSupport-FIL-LON'
)
