SET NOCOUNT ON	

IF OBJECT_ID('tempdb..#Data') IS NOT NULL BEGIN DROP TABLE #Data END;

SELECT 1 AS ID, 0 AS [IsUsed] INTO #Data
INSERT INTO #Data (ID, [IsUsed]) SELECT 2,0
INSERT INTO #Data (ID, [IsUsed]) SELECT 3,0
INSERT INTO #Data (ID, [IsUsed]) SELECT 4,0

DECLARE @ID INT
DECLARE @IsUsed BIT 

DECLARE Data_Cursor CURSOR DYNAMIC FOR 
SELECT ID, IsUsed
FROM #Data
WHERE IsUsed = 0
ORDER BY ID ASC
FOR UPDATE OF IsUsed

OPEN Data_Cursor;

FETCH NEXT FROM Data_Cursor 
INTO @ID, @IsUsed;

WHILE @@FETCH_STATUS = 0
BEGIN
	PRINT 'ID == ' + CONVERT(NVARCHAR(25), @ID)
		
	IF @ID = 2
	BEGIN
		UPDATE #Data SET IsUsed = 1 WHERE ID = 3
		SELECT * FROM #Data WHERE ID = 3
		PRINT 'UPDATE #Data SET IsUsed = 1 WHERE ID = 3 -- Current ID == ' + CONVERT(NVARCHAR(25), @ID)
	END
	
	FETCH NEXT FROM Data_Cursor INTO @ID, @IsUsed
END

CLOSE Data_Cursor;
DEALLOCATE Data_Cursor;

SELECT * 
FROM #Data
ORDER BY ID ASC